// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFAolSoliO7KBXXJbSlPENHdzlkXo_TTo',
    appId: '1:768493635424:web:d5ba5972559afaf0888005',
    messagingSenderId: '768493635424',
    projectId: 'hatgebak-eeb80',
    authDomain: 'hatgebak-eeb80.firebaseapp.com',
    storageBucket: 'hatgebak-eeb80.appspot.com',
    measurementId: 'G-NRGB69RRS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCeXSA4FECHJpLTWkudLz9Dlzf30Hbs6s',
    appId: '1:768493635424:android:7ab3f1a72eb5f77d888005',
    messagingSenderId: '768493635424',
    projectId: 'hatgebak-eeb80',
    storageBucket: 'hatgebak-eeb80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeknMHjSYHP9V8Fs02nheiRgqLcvLFJOU',
    appId: '1:768493635424:ios:6c761423c8466c62888005',
    messagingSenderId: '768493635424',
    projectId: 'hatgebak-eeb80',
    storageBucket: 'hatgebak-eeb80.appspot.com',
    iosBundleId: 'com.example.hatgebak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeknMHjSYHP9V8Fs02nheiRgqLcvLFJOU',
    appId: '1:768493635424:ios:6c761423c8466c62888005',
    messagingSenderId: '768493635424',
    projectId: 'hatgebak-eeb80',
    storageBucket: 'hatgebak-eeb80.appspot.com',
    iosBundleId: 'com.example.hatgebak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFAolSoliO7KBXXJbSlPENHdzlkXo_TTo',
    appId: '1:768493635424:web:2040be60ad3925bc888005',
    messagingSenderId: '768493635424',
    projectId: 'hatgebak-eeb80',
    authDomain: 'hatgebak-eeb80.firebaseapp.com',
    storageBucket: 'hatgebak-eeb80.appspot.com',
    measurementId: 'G-E8BTL9VH6T',
  );
}
